name: publish to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.server }}
          port: ${{ secrets.port }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          script: |
            [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh
            cd ~/Clevertec-ru.github.io
            git checkout main
            git pull
            npm install --legacy-peer-deps
            git stash save --keep-index --include-untracked
            git stash drop
            npm run build
            pm2 restart Clevertec-ru.github.io